---

language: python
sudo: required
dist: trusty
python:
  - 2.7
before_install: # set up the machine
  - sudo apt-get update -qq
  - sudo apt-get install -qq ansible
install: # set up the environment
  - sudo ansible-playbook -i ansible/inventory/localhost.ini ansible/dev.yml -e "travis_build_dir=$TRAVIS_BUILD_DIR"
script: # run the tests
  - source ~/.bashrc # load all the variables that we set up with Ansible, without needing to open another shell
  - export PYSPARK_PYTHON=~/miniconda2/bin/python # tell Spark which Python executable we're using (this only seems to be necessary for TravisCI, not anywhere else)
  - ./run-tests.sh
